# Generated by Django 4.0.3 on 2022-04-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=50)),
                ('responsible_task', models.CharField(max_length=50)),
                ('date_task', models.CharField(max_length=10)),
                ('realized', models.BooleanField(default=False)),
            ],
        ),
    ]
